### ISSUE TITLE
Running testproject throws error

### ISSUE THREAD

**Issue by jayanth1991** [django/channels#431]
https://github.com/django/channels/tree/master/testproject

OS: Ubuntu 16.04 with Linux 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Python version: Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
Django version: 1.9.7
Other software:
asgi_ipc==1.1.0
autobahn==0.14.1
channels==0.14.2
daphne==0.13.1
docutils==0.12
msgpack-python==0.4.7
redis==2.10.5
six==1.10.0
statistics==1.0.3.5
Twisted==16.2.0
txaio==2.5.1
zope.interface==4.2.0

When I run the test program:
```sh
$ daphne testproject.asgi:channel_layer &
$ python manage.py runworker
```
This throws the following backtrace
```sh
$ python manage.py runworker
Traceback (most recent call last):
 File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
   msg = self.format(record)
 File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
   return fmt.format(record)
 File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
   record.message = record.getMessage()
 File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
   msg = msg % self.args
 File "/usr/local/lib/python2.7/dist-packages/channels/asgi.py", line 86, in __str__
   return "%s (%s)" % (self.alias, name_that_thing(self.channel_layer))
 File "/usr/local/lib/python2.7/dist-packages/channels/utils.py", line 23, in name_that_thing
   return name_that_thing(thing.__class__)
 File "/usr/local/lib/python2.7/dist-packages/channels/utils.py", line 16, in name_that_thing
   if hasattr(thing, "__class__") and not isinstance(thing, types.FunctionType):
AttributeError: 'module' object has no attribute 'FunctionType'
Logged from file runworker.py, line 49
2016-11-08 13:18:33,047 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.receive
```

However, when I run the same program with python3, particularly Python 3.5.2 (default, Sep 10 2016, 08:21:44), the program has no errors, here is the log messages
```sh
$ python3 manage.py runworker
2016-11-08 13:18:06,491 - INFO - runworker - Running worker against channel layer default (asgi_ipc.IPCChannelLayer)
2016-11-08 13:18:06,491 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.receive
```

How do I make it work with Python 2.7.

**Comment by jayanth1991** [comment]
There was software conflicts between what is installed globally and what was installed in the virtualenv. Once I uninstalled all the global packages and just used the virtualenv, it worked.
