### ISSUE TITLE
python 3.8.11 broke OriginValidator

### ISSUE THREAD

**Issue by jtremesay-sereema** [django/channels#1716]
Since upgrade from python 3.8.10 to 3.8.11, we observe a AttributeError exception when we use OriginValidator.

Minimal testcase base on the [channels documentation](https://channels.readthedocs.io/en/latest/topics/security.html#websockets): 

```
from django.core.asgi import get_asgi_application
import os

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "proj.settings")
application = get_asgi_application()

from channels.auth import AuthMiddlewareStack
from channels.routing import ProtocolTypeRouter, URLRouter
from channels.security.websocket import OriginValidator
from django.urls import path
from app import consumers

application = ProtocolTypeRouter(
    {
        "http": application,
        "websocket": OriginValidator(
            AuthMiddlewareStack(
                URLRouter([path("hello", consumers.HelloConsumer.as_asgi())])
            ),
            ["localhost"],
        ),
    }
)
```

Stack trace:

```
daphne proj.asgi:application
2021-07-01 14:42:03,153 INFO     Starting server at tcp:port=8000:interface=127.0.0.1
2021-07-01 14:42:03,153 INFO     HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2021-07-01 14:42:03,154 INFO     Configuring endpoint tcp:port=8000:interface=127.0.0.1
2021-07-01 14:42:03,155 INFO     Listening on TCP address 127.0.0.1:8000
127.0.0.1:53331 - - [01/Jul/2021:14:42:07] "GET /" 200 1187
127.0.0.1:53332 - - [01/Jul/2021:14:42:07] "WSCONNECTING /hello" - -
2021-07-01 14:42:08,163 ERROR    Exception inside application: 'NoneType' object has no attribute 'replace'
Traceback (most recent call last):
  File "/Users/jtremesay/projects/django_channels/venv/lib/python3.8/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/Users/jtremesay/projects/django_channels/venv/lib/python3.8/site-packages/channels/security/websocket.py", line 35, in __call__
    if self.valid_origin(parsed_origin):
  File "/Users/jtremesay/projects/django_channels/venv/lib/python3.8/site-packages/channels/security/websocket.py", line 54, in valid_origin
    return self.validate_origin(parsed_origin)
  File "/Users/jtremesay/projects/django_channels/venv/lib/python3.8/site-packages/channels/security/websocket.py", line 73, in validate_origin
    return any(
  File "/Users/jtremesay/projects/django_channels/venv/lib/python3.8/site-packages/channels/security/websocket.py", line 74, in <genexpr>
    pattern == "*" or self.match_allowed_origin(parsed_origin, pattern)
  File "/Users/jtremesay/projects/django_channels/venv/lib/python3.8/site-packages/channels/security/websocket.py", line 98, in match_allowed_origin
    parsed_pattern = urlparse(pattern.lower(), scheme=None)
  File "/usr/local/Cellar/python@3.8/3.8.11/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/parse.py", line 376, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
  File "/usr/local/Cellar/python@3.8/3.8.11/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/parse.py", line 433, in urlsplit
    scheme = _remove_unsafe_bytes_from_url(scheme)
  File "/usr/local/Cellar/python@3.8/3.8.11/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/parse.py", line 422, in _remove_unsafe_bytes_from_url
    url = url.replace(b, "")
AttributeError: 'NoneType' object has no attribute 'replace'
127.0.0.1:53332 - - [01/Jul/2021:14:42:08] "WSDISCONNECT /hello" - -
```

```
$ pip freeze
asgiref==3.4.0
attrs==21.2.0
autobahn==21.3.1
Automat==20.2.0
cffi==1.14.5
channels==3.0.3
constantly==15.1.0
cryptography==3.4.7
daphne==3.0.2
Django==3.2.5
hyperlink==21.0.0
idna==3.2
incremental==21.3.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pyOpenSSL==20.0.1
pytz==2021.1
service-identity==21.1.0
six==1.16.0
sqlparse==0.4.1
Twisted==21.2.0
txaio==21.2.1
zope.interface==5.4.0
```

From what I see in the python 3.8.11 changelog, the exception is caused by [this fix](https://bugs.python.org/issue43882) and the following versions of python should be affected: 3.9.6, 3.8.11, 3.7.11, 3.6.14 and probably >=3.10

**Comment by carltongibson** [comment]
Thanks for the report @jtremesay-sereema. 

Did you have a chance to look at a fix yet? (Looking to do a release so...)

**Comment by jtremesay-sereema** [comment]
Sorry, not yet

**Comment by carltongibson** [comment]
I would imagine an `if pattern is None: return False` might do it... 

https://github.com/django/channels/blob/1c9906654e7774c84b4edaa1a0a075d8a5a15d8e/channels/security/websocket.py#L78-L98

**Comment by carltongibson** [comment]
Fixed by #1719

**Comment by bj00rn** [comment]
Seems this is still an issue in channels 2. 

@carltongibson any hope of getting #1719 backported into a release of channels 2?

**Comment by carltongibson** [comment]
Hi @bj00rn — Sorry no. We (I) don't have the bandwidth to support older versions. You're welcome to backport it yourself though.

**Comment by bj00rn** [comment]
> Hi @bj00rn — Sorry no. We (I) don't have the bandwidth to support older versions. You're welcome to backport it yourself though.

Sure, I gave it a shot in  https://github.com/django/channels/pull/1769
