### ISSUE TITLE
Tests using ApplicationCommunicator are failing after upgrade to 3.0.3

### ISSUE THREAD

**Issue by longedok** [django/channels#1602]
After upgrading channels from 2.4.0 to 3.0.3 (on python3.8), my consumer tests that are using asgiref's ApplicationCommunicator are now failing with the following error `TypeError: __call__() missing 1 required positional argument: 'send'` (full stack-trace attached below). I'm using pytest with pytest-asyncio plugin to run tests.

I'm not sure whether I should report this issue to asgiref instead, but since ApplicationCommunicator was suggested in the docs I created an issue here.

- Your OS and runtime environment, and browser if applicable
MacOs Big Sur 11.1
- A `pip freeze` output showing your package versions
```
asgiref                         3.3.1
channels                        3.0.3
channels-redis                  3.2.0
daphne                          3.0.1
Django                          2.2.17
...truncated...
```
- How you're running Channels
I'm running a test using pytest and pytest-asyncio plugins.
- Console logs and full tracebacks of any errors
```
self = <asgiref.testing.ApplicationCommunicator object at 0x10a4e2280>
timeout = 1

    async def receive_output(self, timeout=1):
        """
        Receives a single message from the application, with optional timeout.
        """
        # Make sure there's not an exception to raise from the task
        if self.future.done():
            self.future.result()
        # Wait and receive the message
        try:
            async with async_timeout(timeout):
>               return await self.output_queue.get()

venv/lib/python3.8/site-packages/asgiref/testing.py:74:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <Queue at 0x10a4e21c0 maxsize=0>

    async def get(self):
        """Remove and return an item from the queue.

        If queue is empty, wait until an item is available.
        """
        while self.empty():
            getter = self._loop.create_future()
            self._getters.append(getter)
            try:
>               await getter
E               asyncio.exceptions.CancelledError

../../../../../.pyenv/versions/3.8.6/lib/python3.8/asyncio/queues.py:163: CancelledError

During handling of the above exception, another exception occurred:

self = <asgiref.testing.ApplicationCommunicator object at 0x10a4e2280>
timeout = 1

    async def receive_output(self, timeout=1):
        """
        Receives a single message from the application, with optional timeout.
        """
        # Make sure there's not an exception to raise from the task
        if self.future.done():
            self.future.result()
        # Wait and receive the message
        try:
            async with async_timeout(timeout):
>               return await self.output_queue.get()

venv/lib/python3.8/site-packages/asgiref/testing.py:74:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <asgiref.timeout.timeout object at 0x10a4c9d00>
exc_type = <class 'asyncio.exceptions.CancelledError'>
exc_val = CancelledError(), exc_tb = <traceback object at 0x10a7a5500>

    async def __aexit__(
        self,
        exc_type: Type[BaseException],
        exc_val: BaseException,
        exc_tb: TracebackType,
    ) -> None:
>       self._do_exit(exc_type)

venv/lib/python3.8/site-packages/asgiref/timeout.py:68:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <asgiref.timeout.timeout object at 0x10a4c9d00>
exc_type = <class 'asyncio.exceptions.CancelledError'>

    def _do_exit(self, exc_type: Type[BaseException]) -> None:
        if exc_type is asyncio.CancelledError and self._cancelled:
            self._cancel_handler = None
            self._task = None
>           raise asyncio.TimeoutError
E           asyncio.exceptions.TimeoutError

venv/lib/python3.8/site-packages/asgiref/timeout.py:105: TimeoutError

During handling of the above exception, another exception occurred:

self = <src.units.tests.test_api_registration.TestRegistrationConsumer object at 0x10a2c9670>
async_service_user = <User: 259996388>, async_unit = <XiScooter: 900256>
event_loop = <_UnixSelectorEventLoop running=False closed=False debug=False>
faker = <faker.generator.Generator object at 0x10a244520>

    async def test_register(self, async_service_user, async_unit, event_loop, faker):
        token = faker.uuid4()

        async with self.communicator(async_service_user) as comm:
            await self.send_input(comm, {"uid": async_unit.pk, "token": token})

            def _register():
                temp_unit = TempUnit.objects.create(token=token, unit=async_unit)
                temp_unit.register()

            delayed_method = self.delay_db_method(event_loop, _register)
>           body, status_code = await self.get_response(comm)

test_api_registration.py:68:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../myproj/utils/testing.py:73: in get_response
    event = await communicator.receive_output(timeout=timeout)
venv/lib/python3.8/site-packages/asgiref/testing.py:78: in receive_output
    self.future.result()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

scope = {'headers': [(b'authorization', b'Bearer 5c93741db83c6a197c8e3d3ba4407c67507ace64')], 'http_version': '1.1', 'method': 'POST', 'path': '/api/myendpoint/registration/', ...}
receive = <bound method Queue.get of <Queue at 0x10a4e2cd0 maxsize=0 _queue=[{'type': 'http.request', 'body': b'{"uid": "900256", "token": "1033a69e-e4b2-4e50-b7ba-1a9bf3613f98"}'}, {'type': 'http.disconnect'}] tasks=2>>
send = <bound method Queue.put of <Queue at 0x10a4e21c0 maxsize=0>>

    async def new_application(scope, receive, send):
        instance = application(scope)
>       return await instance(receive, send)
E       TypeError: __call__() missing 1 required positional argument: 'send'

venv/lib/python3.8/site-packages/asgiref/compatibility.py:34: TypeError
```

**Comment by carltongibson** [comment]
v3 was a major version change, updating to ASGI v3, so all your tests will need adjusting to use the new signature. [Start from the v3.0 release notes](https://channels.readthedocs.io/en/latest/releases/3.0.0.html).
