### ISSUE TITLE
channel_layer attribute from AsyncWebsocketConsumer is None

### ISSUE THREAD

**Issue by clediscover** [django/channels#1678]
# channel_layer attribute from AsyncWebsocketConsumer is None
- I am creating a chat application in which the database (sqlite3) is used on my asynchronous consumer. My asynchronous consumer works fine even if I am doing Django ORM. 
- The error happens when I used **channel_layer** attribute. Such as for group_add() and group_discard(). The **channel_layer** attribute becomes None.
- I also followed the [tutorial](https://channels.readthedocs.io/en/stable/tutorial/index.html) from this django/channels docs. The application that I made there is working fine even if it is using **channel_layer** attribute. But on that project (from tutorial), I'm not doing any related Django ORM on asynchronous consumer.
- The OS that I am working on is Ubuntu 20.04 LTS.
- I run the app using the ASGI/Channels development server.

### Modules that I use
```
Django==3.1.7
channels==3.0.3
channels-redis==3.2.0
```

### Here is the error where channel_layer attribute is none:
```
await self.channel_layer.group_add(
AttributeError: 'NoneType' object has no attribute 'group_add'`
```

### Here is the full console log error:
```
System check identified no issues (0 silenced).
April 16, 2021 - 17:01:23
Django version 3.1.7, using settings 'django_channels_chatapp.settings'
Starting ASGI/Channels version 3.0.3 development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
HTTP GET /chat/1/ 200 [0.05, 127.0.0.1:60500]
WebSocket HANDSHAKING /ws/chat/1/ [127.0.0.1:60502]
Not Found: /favicon.ico
Exception inside application: 'NoneType' object has no attribute 'group_add'
Traceback (most recent call last):
  File "/home/ace/.local/lib/python3.8/site-packages/channels/staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "/home/ace/.local/lib/python3.8/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/home/ace/.local/lib/python3.8/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/home/ace/.local/lib/python3.8/site-packages/channels/sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/home/ace/.local/lib/python3.8/site-packages/channels/auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "/home/ace/.local/lib/python3.8/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/home/ace/.local/lib/python3.8/site-packages/channels/routing.py", line 150, in __call__
    return await application(
  File "/home/ace/.local/lib/python3.8/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/home/ace/.local/lib/python3.8/site-packages/channels/consumer.py", line 62, in __call__
    await await_many_dispatch([receive], self.dispatch)
  File "/home/ace/.local/lib/python3.8/site-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/home/ace/.local/lib/python3.8/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/home/ace/.local/lib/python3.8/site-packages/channels/generic/websocket.py", line 175, in websocket_connect
    await self.connect()
  File "/home/ace/Documents/django_channels_chatapp/core/consumers.py", line 43, in connect
    await self.channel_layer.group_add(
AttributeError: 'NoneType' object has no attribute 'group_add'
WebSocket DISCONNECT /ws/chat/1/ [127.0.0.1:60502]
```

**Comment by yedpodtrzitko** [comment]
please show your code too

**Comment by clediscover** [comment]
> please show your code too

```python
class ChatConsumer(AsyncWebsocketConsumer):
    async def connect(self):
        # Setup the user1 and user2
        user1 = await get_user(self.scope)
        user2_pk = self.scope['url_route']['kwargs']['user2_pk']
        user2 = await self.get_usermodel(pk=user2_pk)

        # Checks if user1 is authenticated, if not reject the request.
        # user1 should be authenticated because it will be the one who 
        # will become the sender to chat
        if not user1.is_authenticated:
            await self.close()
        
        # Setup user1 and user2 username, and 
        # user1 sender and user2 receiver model
        self.user1_username = await database_sync_to_async(user1.get_username)()
        self.user2_username = await database_sync_to_async(user2.get_username)()
        self.user1_sender = await self.get_sendermodel(user=user1)
        self.user2_receiver = await self.get_sendermodel(user=user2)

        # Get the key from ChatKeyModel and create room name
        chatkey = await database_sync_to_async(ChatKeyModel.get_by_usernames)(
            [
                self.user1_username,
                self.user2_username
            ]
        )
        key = await self.get_key_from_chatkeymodel(chatkey)
        self.room_name = f'chat_room_{key}'
        
        # Add the room name to channel layer
        await self.channel_layer.group_add(
            self.room_name,
            self.channel_name
        )

        # Accept the request
        await self.accept()
    
    async def disconnect(self, close_code):
        # Remove the room name to channel layer
        await self.channel_layer.group_discard(
            self.room_name,
            self.channel_name
        )
    
    async def receive(self, text_data):
        # Decode the message
        text_data_as_json = json.loads(text_data)
        message = text_data_as_json['message']

        # Save the message to database
        await self.create_chatmodel(
            sender=self.user1_sender,
            receiver=self.user2_receiver,
            text=message
        )

        # Send the message to channel layer
        await self.channel_layer.group_send(
            self.room_name,
            {
                'type': 'send.message',
                'message': message
            }
        )
    
    async def send_message(self, event):
        # Get the message from event then make it as json format
        message = json.dumps({'message': event['message']})

        # Send the message to websocket
        await self.send(
            text_data=message
        )

    @database_sync_to_async
    def get_usermodel(self, **kwargs):
        return User.objects.get(**kwargs)
    
    @database_sync_to_async
    def get_receivermodel(self, **kwargs):
        return ReceiverModel.objects.get(**kwargs)
    
    @database_sync_to_async
    def get_sendermodel(self, **kwargs):
        return SenderModel.objects.get(**kwargs)
    
    @database_sync_to_async
    def get_key_from_chatkeymodel(self, chatkey):
        return chatkey.key
    
    @database_sync_to_async
    def create_chatmodel(self, **kwargs):
        return ChatModel.objects.create(**kwargs)
```

- The error happens here:
```python
# Add the room name to channel layer
await self.channel_layer.group_add(
  self.room_name,
  self.channel_name
)
```

**Comment by clediscover** [comment]
# Solved
- I finally solved the problem. The problems appears because of my `CHANNELS_LAYER` from my project settings, it should be `CHANNEL_LAYERS`. I see that `get_channel_layer()` method from **channels/layers.py** (from this repo) returns None when there is no `CHANNEL_LAYERS` configured in settings. I guess it should be better to show some warnings when we can't use channel_layers.
- The **channel_layers** attribute from websocket consumer becomes None when there is no `CHANNEL_LAYERS` configured in settings. Like when it is empty dict or unset.
